#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const __merge = require('lodash/merge');
const defaultConfig = JSON.parse(fs.readFileSync(__dirname + '/.testsconfig', 'utf8'));
const config = JSON.parse(fs.readFileSync('.testsconfig', 'utf8'));
// configs
const finalConfig = __merge({}, defaultConfig, config || {}, {
	karma: {
		webpack: {
			module: {
				loaders: [{
					test: /\.js$/,
					exclude: /node_modules/,
					loader: 'babel-loader'
				}, {
					test: /\.html$/,
					loader: 'html'
				}]
			},
			node: {
				fs: "empty"
			}
		},
		webpackMiddleware: {
			stats: 'minimal',
			noInfo: true
		}
	}
});

// karma
if (finalConfig.karma.files.length) {
	// start and run server
	const Server = require('karma').Server
	const server = new Server(finalConfig.karma, function(exitCode) {
		console.log('All done folks! exit(' + exitCode + ')');
		process.exit(exitCode);
	});
	server.start();
}
